spring.application.name=Graduation-project

# =============================================
# PostgreSQL Database Configuration
# =============================================
spring.datasource.url=jdbc:postgresql://localhost:5432/graduation_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# =============================================
# JPA / Hibernate
# =============================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# =============================================
# JWT & Google OAuth2
# =============================================
jwt.key=${JWT_KEY:6gj3ijzRCKoZBfMWDghcHzAxjCcH4Kb7Z1XSzsBZM4z}
google.client.id=${GOOGLE_CLIENT_ID:547880381048-lau7t5mle81d9ba1o0ed532c3qthmfam.apps.googleusercontent.com}
